### ISSUE TITLE
Init command not working

### ISSUE THREAD

**Issue by devrsi0n** [FullHuman/tosin#3]
**Describe the bug**
`npx tosin init` not working
**Screenshots**

![image](https://user-images.githubusercontent.com/7880675/58602215-9d8a6280-82be-11e9-8b45-b1e71c64215a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version of Tosin [e.g. 1.0.0]

**Comment by Ffloriel** [comment]
Thanks for reporting this, I forgot to specify the path to the `bin` indeed. Fixed in version 1.0.2.
Let me know if you find another issue.
